name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ctest

