name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - run: python -m pip install cpplint

    - run: cpplint --recursive .

  build:
    needs:
      ["cpplint"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ctest

